runtime: go114

main: ./server

handlers:
  - url: /
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html
  - url: /(.*\.(html|js))$
    static_files: frontend/dist/\1
    upload: frontend/dist/.*\.(html|js)$
