---
services:
  gcloud_datastore:
    build:
      context: .
      dockerfile: gcp/datastore/Dockerfile
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/gcloud_datastore:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/gcloud_datastore
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/gcloud_datastore:${TAG_NAME:-latest}
    init: true
    tty: true
    environment:
      DATASTORE_PROJECT_ID: app
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:${GCLOUD_DATASOURCE_PORT}
      GCLOUD_DATASOURCE_PORT: ${GCLOUD_DATASOURCE_PORT}
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      PROJECT_ID: app
      DATASTORE_EMULATOR_HOST: "gcloud_datastore:${GCLOUD_DATASOURCE_PORT}"
      PORT: ${PORT}
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      PORT: ${PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"
