---
services:
  server:
    build:
      target: build
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/server-dev:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/server-dev
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/server-base:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/server-base
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/server-dev:${TAG_NAME:-latest}
    volumes:
      - ./server:/go/app/server
  frontend:
    build:
      target: build
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-dev:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-dev
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-base:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-base
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-dev:${TAG_NAME:-latest}
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      server:
        condition: service_healthy
