---
name: block-merge-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  block-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6.3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            for (const label of context.payload.pull_request.labels) {
              if (label.name === 'duplicate') {
                return 1;
              }
            }

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
