---
name: check-fail-notify
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - master
jobs:
  check-fail-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get diff
        id: get_diff
        run: |
          workflows_dir=.github/workflows
          fail_notify_workflow_file="${workflows_dir}/fail-notify.yml"
          workflows="$(find "${workflows_dir}" -not -path "${fail_notify_workflow_file}" -type f -exec yq '.name' {} \; | sort | sed -e 's/^\(.*\)$/"\1"/g' | tr '\n' ',' | sed -e 's/,$//g')"
          yq -i ".on.workflow_run.workflows=[${workflows}]" "${fail_notify_workflow_file}"
          diff="$(git diff)"
          echo "${diff}"
          diff="${diff//'%'/'%25'}"
          diff="${diff//$'\n'/'%0A'}"
          diff="${diff//$'\r'/'%0D'}"
          echo "diff=${diff}" >>"${GITHUB_OUTPUT}"
      - if: steps.get_diff.outputs.diff != ''
        run: exit 1
