name: 'Dependency Review'
on:
  pull_request:
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/dependency-review-action@v3.1.0
