name: 'Dependency Review'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/dependency-review-action@v3.0.4
