name: 'Dependency Review'
on:
  pull_request:
  merge_group:
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/dependency-review-action@v3.1.0
