---
name: fix-fail-notify
on:
  pull_request:
  merge_group:
permissions: read-all
jobs:
  fix-fail-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1.11.0
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
          token: ${{steps.generate_token.outputs.token}}
      - run: bash "${GITHUB_WORKSPACE}/scripts/fix_fail_notify/fix_fail_notify/fix_fail_notify.sh"
      - uses: dev-hato/actions-diff-pr-management@v1.1.12
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          branch-name-prefix: fix-fail-notify
          pr-title-prefix: fail-notifyが間違ってたので直してあげたよ！
