---
name: fix-fail-notify
on:
  pull_request:
  merge_group:
permissions: read-all
jobs:
  fix-fail-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
          token: ${{secrets.CREATE_WORKFLOW_CI_TOKEN}}
      - run: bash "${GITHUB_WORKSPACE}/scripts/fix_fail_notify/fix_fail_notify/fix_fail_notify.sh"
      - uses: dev-hato/actions-diff-pr-management@v1.1.10
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-fail-notify
          pr-title-prefix: fail-notifyが間違ってたので直してあげたよ！
