---
name: ghalint
on:
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
  statuses: write
jobs:
  ghalint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - run: go install github.com/suzuki-shunsuke/ghalint/cmd/ghalint
      - run: ghalint run
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
