---
name: renovate-config-validator

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .node-version
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.npm
          key: node-cache-${{ runner.os }}-npm-${{ github.workflow }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-cache-${{ runner.os }}-npm-${{ github.workflow }}-${{ hashFiles('package-lock.json') }}
            node-cache-${{ runner.os }}-npm-${{ github.workflow }}-
      - run: bash "${GITHUB_WORKSPACE}/scripts/renovate_config_validator/renovate_config_validator/run_validator.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
